name: Deploy to FrontEnd

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker login -u "docke20" -p "Docker@2005"
      - run: docker build -t docke20/docker-react -f Dockerfile.dev .
